---
title: "ncairquality_analysis"
author: "Gabrielle Ruehle"
date: "10/3/2020"
output: html_document
---

```{r}
library(readr)
NCairquality <- read_csv("~/Virtual Sneks 2/NCairquality.csv")
NCairquality <- filter(NCairquality, majorlocation != "Wilmington")
head(NCairquality)
nrow(NCairquality)
```
```{r}
NCairquality%>% 
  group_by(majorlocation) %>%
  summarise(count = n(),
            pm10_avg = mean(pm10, na.rm = TRUE),
            pm25_avg = mean(pm25, na.rm = TRUE),
            so2_avg = mean(so2, na.rm = TRUE), 
            o3_avg = mean(o3, na.rm = TRUE),
            co_avg = mean(co, na.rm = TRUE),
            no2_avg = mean(no2, na.rm = TRUE))
```


# pm10 by major location

```{r}
pm10notNA <- filter(NCairquality, !is.na(pm10))

#anova
aov(pm10 ~ majorlocation, data=pm10notNA) %>% summary()

#differences
aov(pm10 ~ majorlocation, data=pm10notNA) %>% TukeyHSD()

#ggplot
library(ggplot2)
ggplot(NCairquality, aes(as.factor(majorlocation), pm10)) + 
  geom_boxplot(aes_string(colour="majorlocation", fill="majorlocation")) + 
  theme_classic() +
  xlab("Major Location")+
  stat_summary(geom = "crossbar", width=0.65, fatten=0, color="white", fun.data = function(x){ return(c(y=median(x), ymin=median(x), ymax=median(x))) }) + 
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Set2") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

library(ggplot2)
ggplot(NCairquality, aes(as.factor(majorlocation), pm10)) + 
  geom_boxplot(aes_string(colour="majorlocation", fill="majorlocation")) + 
  theme_classic() +
  xlab("Major Location")+
  stat_summary(geom = "crossbar", width=0.65, fatten=0, color="white", fun.data = function(x){ return(c(y=median(x), ymin=median(x), ymax=median(x))) }) + 
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Set2") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_cartesian(ylim = c(0,30))
```

# pm10 by location
```{r}
pm10notNA <- filter(NCairquality, !is.na(pm10))

#anova
aov(pm10 ~ location, data=pm10notNA) %>% summary()

#differences
aov(pm10 ~ location, data=pm10notNA) %>% TukeyHSD()

#ggplot
library(ggplot2)
ggplot(NCairquality, aes(as.factor(location), pm10)) + 
  geom_boxplot(aes_string(colour="location", fill="location")) + 
  theme_classic() +
  xlab("Location")+
  stat_summary(geom = "crossbar", width=0.65, fatten=0, color="white", fun.data = function(x){ return(c(y=median(x), ymin=median(x), ymax=median(x))) }) + 
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Set2") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(NCairquality, aes(as.factor(location), pm10)) + 
  geom_boxplot(aes_string(colour="location", fill="location")) + 
  theme_classic() +
  xlab("Location")+
  stat_summary(geom = "crossbar", width=0.65, fatten=0, color="white", fun.data = function(x){ return(c(y=median(x), ymin=median(x), ymax=median(x))) }) + 
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Set2") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  coord_cartesian(ylim = c(0,30))
```

# pm25 by major location

```{r}
pm25notNA <- filter(NCairquality, !is.na(pm25))

#anova
aov(pm25 ~ majorlocation, data=pm25notNA) %>% summary()

#differences
aov(pm25 ~ majorlocation, data=pm25notNA) %>% TukeyHSD()

#ggplot
library(ggplot2)
ggplot(NCairquality, aes(as.factor(majorlocation), pm25)) + 
  geom_boxplot(aes_string(colour="majorlocation", fill="majorlocation")) + 
  theme_classic() +
  xlab("Major Location")+
  stat_summary(geom = "crossbar", width=0.65, fatten=0, color="white", 
               fun.data = function(x){ return(c(y=median(x), ymin=median(x), ymax=median(x))) }) + 
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Set2") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

library(ggplot2)
ggplot(NCairquality, aes(as.factor(majorlocation), pm25)) + 
  geom_boxplot(aes_string(colour="majorlocation", fill="majorlocation")) + 
  theme_classic() +
  xlab("Major Location")+
  stat_summary(geom = "crossbar", width=0.65, fatten=0, color="white", 
               fun.data = function(x){ return(c(y=median(x), ymin=median(x), ymax=median(x))) }) + 
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Set2") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_cartesian(ylim=c(0,20))
```


# pm 25 by location 
```{r}
pm25notNA <- filter(NCairquality, !is.na(pm25))

#anova
aov(pm25 ~ location, data=pm25notNA) %>% summary()

#differences
aov(pm25 ~ location, data=pm25notNA) %>% TukeyHSD()

#ggplot
library(ggplot2)
ggplot(NCairquality, aes(as.factor(location), pm25)) + 
  geom_boxplot(aes_string(colour="location", fill="location")) + 
  theme_classic() +
  xlab("Location")+
  stat_summary(geom = "crossbar", width=0.65, fatten=0, color="white", 
               fun.data = function(x){ return(c(y=median(x), ymin=median(x), ymax=median(x))) }) + 
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Set2") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


ggplot(NCairquality, aes(as.factor(location), pm25)) + 
  geom_boxplot(aes_string(colour="location", fill="location")) + 
  theme_classic() +
  xlab("Location")+
  stat_summary(geom = "crossbar", width=0.65, fatten=0, color="white", 
               fun.data = function(x){ return(c(y=median(x), ymin=median(x), ymax=median(x))) }) + 
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Set2") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_cartesian(ylim=c(0,20))
```





# o3 by major location
```{r}
o3notNA <- filter(NCairquality, !is.na(o3))

#anova
aov(o3 ~ majorlocation, data=o3notNA) %>% summary()

#differences
aov(o3 ~ majorlocation, data=o3notNA) %>% TukeyHSD()

#ggplot
library(ggplot2)
ggplot(NCairquality, aes(as.factor(majorlocation), o3)) + 
  geom_boxplot(aes_string(colour="majorlocation", fill="majorlocation")) + 
  theme_classic() +
  xlab("Major Location")+
  stat_summary(geom = "crossbar", width=0.65, fatten=0, color="white", 
               fun.data = function(x){ return(c(y=median(x), ymin=median(x), ymax=median(x))) }) + 
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Set2") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

# o3 by location 
```{r}
o3notNA <- filter(NCairquality, !is.na(o3))

#anova
aov(o3 ~ location, data=o3notNA) %>% summary()

#differences
aov(o3 ~ location, data=o3notNA) %>% TukeyHSD()

#ggplot
library(ggplot2)
ggplot(NCairquality, aes(as.factor(location), o3)) + 
  geom_boxplot(aes_string(colour="location", fill="location")) + 
  theme_classic() +
  xlab("Location")+
  stat_summary(geom = "crossbar", width=0.65, fatten=0, color="white", 
               fun.data = function(x){ return(c(y=median(x), ymin=median(x), ymax=median(x))) }) + 
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Set2") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


```

# pm 10 over time

```{r}
NCairquality %>%
  mutate(month = lubridate::month(local)) %>%
  filter(!is.na(pm10)) %>%
  group_by(month) %>%
  summarise(avg_pm10 = mean(pm10)) %>%
  ggplot(aes(month, avg_pm10)) + geom_line()

NCairquality %>%
  mutate(month = lubridate::month(local)) %>%
  filter(!is.na(pm10)) %>%
  group_by(month, majorlocation) %>%
  summarise(avg_pm10 = mean(pm10)) %>%
  ggplot(aes(month, avg_pm10, color = majorlocation)) +
  geom_line() +
  theme_minimal() +
  scale_x_continuous(breaks = scales::pretty_breaks())
```


# pm 25 over time

```{r}
NCairquality %>%
  mutate(month = lubridate::month(local)) %>%
  filter(!is.na(pm25)) %>%
  group_by(month) %>%
  summarise(avg_pm25 = mean(pm25)) %>%
  ggplot(aes(month, avg_pm25)) + geom_line() +
  scale_x_continuous(breaks = scales::pretty_breaks())

NCairquality %>%
  mutate(month = lubridate::month(local)) %>%
  filter(!is.na(pm25)) %>%
  group_by(month, majorlocation) %>%
  summarise(avg_pm25 = mean(pm25)) %>%
  ggplot(aes(month, avg_pm25, color = majorlocation)) +
  geom_line() +
  theme_minimal() +
  scale_x_continuous(breaks = scales::pretty_breaks())
```


# o3 over time

```{r}
NCairquality %>%
  mutate(month = lubridate::month(local)) %>%
  filter(!is.na(o3)) %>%
  group_by(month) %>%
  summarise(avg_o3 = mean(o3)) %>%
  ggplot(aes(month, avg_o3)) + geom_line() +
  scale_x_continuous(breaks = scales::pretty_breaks())

NCairquality %>%
  mutate(month = lubridate::month(local)) %>%
  filter(!is.na(o3)) %>%
  group_by(month, majorlocation) %>%
  summarise(avg_o3 = mean(o3)) %>%
  ggplot(aes(month, avg_o3, color = majorlocation)) +
  geom_line() +
  theme_minimal() +
  scale_x_continuous(breaks = scales::pretty_breaks())
```


```{r, warning=FALSE message=FALSE}
NCairquality %>%
  mutate(month_yr = format(as.Date(local), "%Y-%m")) %>%
  filter(!is.na(o3)) %>%
  group_by(month_yr) %>%
  summarise(avg_o3 = mean(o3)) %>%
  ggplot(aes(month_yr, avg_o3)) + 
    geom_point() +
    geom_line() +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylab("Average O3") + xlab("Year-Month")
```

```{r}
o3_year_month <- NCairquality %>%
  mutate(month = lubridate::month(local)) %>%
  mutate(year = lubridate::year(local)) %>%
  filter(!is.na(o3)) %>%
  group_by(month, year) %>%
  summarise(avg_o3 = mean(o3)) %>% 
  arrange(year)
o3_year_month
```
```{r}
y <- x
y %>%
  filter(month==1) %>%
  merge(filter(x, month == 2), by = "year", all = TRUE) %>%
  merge(filter(x, month == 3), by = "year", all = TRUE) %>%
  merge(filter(x, month == 4), by = "year", all = TRUE) %>%
  merge(filter(x, month == 5), by = "year", all = TRUE) %>%
  merge(filter(x, month == 6), by = "year", all = TRUE) %>%
  merge(filter(x, month == 7), by = "year", all = TRUE) %>%
  merge(filter(x, month == 8), by = "year", all = TRUE) %>%
  merge(filter(x, month == 9), by = "year", all = TRUE) %>%
  merge(filter(x, month == 10), by = "year", all = TRUE) %>%
  merge(filter(x, month == 11), by = "year",all = TRUE) %>%
  merge(filter(x, month == 12), by = "year", all = TRUE) %>%
  subset(select = c(1,3,5,7,9,11,13,15,17,19,21,23,25)) %>%
  setNames(c("year", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Sep", "Oct", "Nov", "Dec"))
 
plot.ts(y)


z <- o3_year_month$avg_o3
z <- z[-1 ]
z
o3timeseries <- ts(z, start=2018, frequency = 12)
o3timeseries

plot.ts(o3timeseries)
```

```{r}
o3timeseriescomponents <- decompose(o3timeseries)

o3timeseriescomponents$seasonal

plot(o3timeseriescomponents)
```
#seasonally adjusting
```{r}
o3timeseriesseasonallyadjusted <- o3timeseries - o3timeseriescomponents$seasonal

plot(o3timeseriesseasonallyadjusted)
```

# Holt-Winters Exponential Smoothing
```{r}
o3timeseriesforecasts <- HoltWinters(o3timeseries)
o3timeseriesforecasts
```
```{r}
plot(o3timeseriesforecasts)
```
```{r}
library(forecast)
o3timeseriesforecasts2 <- forecast(o3timeseriesforecasts, h=12)
plot(o3timeseriesforecasts2)
```


```{r}
plot.ts(o3timeseriesforecasts2$residuals)
abline(0,0)
hist(o3timeseriesforecasts2$residuals)
```






