---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
```

```{r}
library(readr)
OpenAQDurham <- read_csv("C:/Users/gabri/OneDrive/Documents/CDC2020/OpenAQDurham.csv")

head(OpenAQDurham)
```
```{r}
unique(OpenAQDurham$latitude)
```


```{r}
library(readr)
OpenAQSanFran <- read_csv("C:/Users/gabri/OneDrive/Documents/CDC2020/OpenAQSanFran.csv")
head(OpenAQSanFran)
```
```{r}
unique(OpenAQSanFran$parameter)
```


```{r}
nrow(OpenAQDurham)
nrow(OpenAQSanFran)
```

```{r}
test <- head(OpenAQDurham, 15)
test
```


```{r}
test1 <- OpenAQDurham %>% group_by(location, local) %>%
  filter(parameter=="pm10") %>%
  summarise(pm10 = value)

test2 <- OpenAQDurham %>% group_by(location, local) %>%
  filter(parameter=="pm25") %>%
  summarise(pm25 = value)

test3 <- OpenAQDurham %>% group_by(location, local) %>%
  filter(parameter=="so2") %>%
  summarise(so2 = value)

test4 <- OpenAQDurham %>% group_by(location, local) %>%
  filter(parameter=="o3") %>%
  summarise(o3 = value)

test5 <- OpenAQDurham %>% group_by(location, local) %>%
  filter(parameter=="co") %>%
  summarise(co = value)

test6 <- OpenAQDurham %>% group_by(location, local) %>%
  filter(parameter=="no2") %>%
  summarise(no2 = value)

test7 <- OpenAQDurham %>% group_by(location,local) %>% 
  summarise(latitude = mean(latitude), longitude = mean(longitude))

Durhamtest <- merge(test1, test2, by = c("location", "local"), all = TRUE) %>%
  merge(test3, by = c("location", "local"), all = TRUE) %>%
  merge(test4, by = c("location", "local"), all = TRUE) %>%
  merge(test5, by = c("location", "local"), all = TRUE) %>%
  merge(test6, by = c("location", "local"), all = TRUE) %>%
  merge(test7, by = c("location", "local"), all = TRUE)

head(Durhamtest, 30)
nrow(Durhamtest)
```
```{r}
cleaning.function <- function(df, x) {
  
test1 <- df %>% group_by(location, local) %>%
  filter(parameter=="pm10") %>%
  summarise(pm10 = value)

test2 <- df %>% group_by(location, local) %>%
  filter(parameter=="pm25") %>%
  summarise(pm25 = value)

test3 <- df %>% group_by(location, local) %>%
  filter(parameter=="so2") %>%
  summarise(so2 = value)

test4 <- df %>% group_by(location, local) %>%
  filter(parameter=="o3") %>%
  summarise(o3 = value)

test5 <- df %>% group_by(location, local) %>%
  filter(parameter=="co") %>%
  summarise(co = value)

test6 <- df %>% group_by(location, local) %>%
  filter(parameter=="no2") %>%
  summarise(no2 = value)

test7 <- df %>% group_by(location,local) %>% 
  summarise(latitude = mean(latitude), longitude = mean(longitude))

df_final <- merge(test1, test2, by = c("location", "local"), all = TRUE) %>%
  merge(test3, by = c("location", "local"), all = TRUE) %>%
  merge(test4, by = c("location", "local"), all = TRUE) %>%
  merge(test5, by = c("location", "local"), all = TRUE) %>%
  merge(test6, by = c("location", "local"), all = TRUE) %>%
  merge(test7, by = c("location", "local"), all = TRUE)

df_final$majorlocation <- x

return(df_final)
}

```
```{r}
Durham <- cleaning.function(OpenAQDurham, "Durham")
head(Durham)
```

```{r}
bryson <- read_csv("C:/Users/gabri/OneDrive/Documents/CDC2020/bryson_allvars.txt")
bryson <- cleaning.function(bryson, "Bryson")
head(bryson)
```

```{r}

charlotte_allvars <- read_csv("C:/Users/gabri/OneDrive/Documents/CDC2020/charlotte_allvars.txt")
head(charlotte_allvars)

charlotte <- cleaning.function(charlotte_allvars, "Charlotte")
head(charlotte)


cranberry_allvars <- read_csv("C:/Users/gabri/OneDrive/Documents/CDC2020/cranberry_allvars.txt")

cranberry <- cleaning.function(cranberry_allvars, "Cranberry")
head(cranberry)


greensboro_o3 <- read_csv("C:/Users/gabri/OneDrive/Documents/CDC2020/greensboro_o3.txt")

greensboro_o3 <- cleaning.function(greensboro_o3, "Greensboro")
head(greensboro_o3)


greensboro_pm <- read_csv("C:/Users/gabri/OneDrive/Documents/CDC2020/greensboro_pm.txt")

greensboro_pm <- cleaning.function(greensboro_pm, "Greensboro")
head(greensboro_pm)


moreheadcity_allvars <- read_csv("C:/Users/gabri/OneDrive/Documents/CDC2020/moreheadcity_allvars.txt")

moreheadcity <- cleaning.function(moreheadcity_allvars, "Morehead City")
head(moreheadcity)


raleigh <- read_csv("C:/Users/gabri/OneDrive/Documents/CDC2020/raleigh.txt")

raleigh <- cleaning.function(raleigh, "Raleigh")
head(raleigh)


wilmington <- read_csv("C:/Users/gabri/OneDrive/Documents/CDC2020/wilmington.txt")

wilmington <- cleaning.function(wilmington, "Wilmington")
head(wilmington)
```

```{r}
test1 <- head(greensboro_o3)
test2 <- head(greensboro_pm)

full_join(greensboro_o3, greensboro_pm, by= c("location", "local"), all = TRUE)
```

